### ISSUE TITLE
STA9750 haolinnn MiniProject #00

### ISSUE THREAD

**Issue by haolinnn** [haolinnn/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://haolinnn.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @haolinnn !

Peer Feedback:

- @YantingZhao11
- @mt1536
- @edodia

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @haolinnn.

Website URL should be: https://haolinnn.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @haolinnn and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by mt1536** [comment]
Hi @haolinnn,

I like that the link works. My suggestions for improvement are:
- Update [D]isney
- Review for typos

Regards,
mt1536

**Comment by YantingZhao11** [comment]
Hi @haolinnn,

The website is working, and the brief bullet points about yourself look good. I suggest including your name and checking for any punctuations. 

Thanks,
Yanting

**Comment by Edodia** [comment]
Hi @haolinnn <https://github.com/haolinnn>, I like the theme of your
website. I would personally add some professional links to the site, such
as your LinkedIn profile or resume.

Best,
Edosa
